topics:
  -
    topic: /map
    type: nav_msgs/msg/OccupancyGrid
    queue_size: 10
    qos:
      history: keep_last
      durability: transient_local
      reliability: reliable
  -
    topic: /odometry/imu
    type: nav_msgs/msg/Odometry
    queue_size: 10
    qos:
      history: keep_last
      durability: transient_local
      reliability: reliable
  -
    topic: /tf
    type: tf2_msgs/msg/TFMessage
    queue_size: 10
    qos:
      history: keep_last
      durability: transient_local
      reliability: reliable
  -
    topic: /points_raw
    type: sensor_msgs/msg/PointCloud2
    queue_size: 10
    qos:
      history: keep_last
      durability: volatile
      reliability: best_effort
  -
    topic: /scan
    type: sensor_msgs/msg/LaserScan
    queue_size: 1
    qos:
      history: keep_last
      durability: volatile
      reliability: best_effort
  -
    topic: /tf_static
    type: tf2_msgs/msg/TFMessage
    queue_size: 10
    qos:
      history: keep_last
      durability: transient_local
      reliability: reliable
  -
    topic: /cmd_vel
    type: geometry_msgs/msg/Twist
    
  -
    topic: /recognized_class
    type: std_msgs/msg/String
  -
    topic: /camera/left/right/camera_info
    type: sensor_msgs/msg/CameraInfo
  -
    topic: /camera/left/right/image_raw
    type: sensor_msgs/msg/Image
  -
    topic: /camera/right/left/camera_info
    type: sensor_msgs/msg/CameraInfo
  -
    topic: /camera/right/left/image_raw
    type: sensor_msgs/msg/Image
  -
    topic: /camera/color/camera_info
    type: sensor_msgs/msg/CameraInfo
  -
    topic: /camera/color/image_raw
    type: sensor_msgs/msg/Image




